// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	resumesFieldNames          = builder.RawFieldNames(&Resumes{})
	resumesRows                = strings.Join(resumesFieldNames, ",")
	resumesRowsExpectAutoSet   = strings.Join(stringx.Remove(resumesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	resumesRowsWithPlaceHolder = strings.Join(stringx.Remove(resumesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	resumesModel interface {
		Insert(ctx context.Context, data *Resumes) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Resumes, error)
		Update(ctx context.Context, data *Resumes) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultResumesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Resumes struct {
		Id         uint64         `db:"id"`
		UserId     uint64         `db:"user_id"`
		OssUrl     string         `db:"oss_url"`
		ParsedJson sql.NullString `db:"parsed_json"`
		ParseState string         `db:"parse_state"`
		CreatedAt  time.Time      `db:"created_at"`
	}
)

func newResumesModel(conn sqlx.SqlConn) *defaultResumesModel {
	return &defaultResumesModel{
		conn:  conn,
		table: "`resumes`",
	}
}

func (m *defaultResumesModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultResumesModel) FindOne(ctx context.Context, id uint64) (*Resumes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", resumesRows, m.table)
	var resp Resumes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultResumesModel) Insert(ctx context.Context, data *Resumes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, resumesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.OssUrl, data.ParsedJson, data.ParseState)
	return ret, err
}

func (m *defaultResumesModel) Update(ctx context.Context, data *Resumes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, resumesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.OssUrl, data.ParsedJson, data.ParseState, data.Id)
	return err
}

func (m *defaultResumesModel) tableName() string {
	return m.table
}
