Name: app-apis
Host: 0.0.0.0
Port: 8888
Mode: pro
Timeout: 12000

Middlewares:
  Log: false

Log:
  Mode: console
  Encoding: json
  Level: ${LOG_LEVEL}
  Stat: ${LOG_STAT}

Auth:
  AccessSecret: "${AUTH_ACCESS_SECRET}"
  AccessExpire: ${AUTH_ACCESS_EXPIRE}

UserRpc:
  Timeout: 10000
  Endpoints:
    - ${USER_RPC_ENDPOINT}

InterviewRpc:
  Endpoints:
    - ${INTERVIEW_RPC_ENDPOINT}

QuestionRpc:
  Endpoints:
    - ${QUESTION_RPC_ENDPOINT}

OSS:
  Region: "${OSS_REGION}"
  Endpoint: "${OSS_ENDPOINT}"
  Bucket: "${OSS_BUCKET}"
  AccessKeyID: "${OSS_ACCESS_KEY_ID}"
  AccessKeySecret: "${OSS_ACCESS_KEY_SECRET}"
  ObjectURLPrefix: "${OSS_OBJECT_URL_PREFIX}"

Websocket:
  PublicUrl: "${WEBSOCKET_PUBLIC_URL}"
