// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package user

import (
	"context"

	"github.com/rotbit/whetstone/app/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductCreditReq  = pb.DeductCreditReq
	DeductCreditResp = pb.DeductCreditResp
	GetUserReq       = pb.GetUserReq
	RefundCreditReq  = pb.RefundCreditReq
	RefundCreditResp = pb.RefundCreditResp
	RegisterReq      = pb.RegisterReq
	RegisterResp     = pb.RegisterResp
	UserInfo         = pb.UserInfo

	User interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserInfo, error)
		// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
		DeductCredit(ctx context.Context, in *DeductCreditReq, opts ...grpc.CallOption) (*DeductCreditResp, error)
		// 面试异常中断时回补次数（同样以 session_id 幂等）
		RefundCredit(ctx context.Context, in *RefundCreditReq, opts ...grpc.CallOption) (*RefundCreditResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
func (m *defaultUser) DeductCredit(ctx context.Context, in *DeductCreditReq, opts ...grpc.CallOption) (*DeductCreditResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DeductCredit(ctx, in, opts...)
}

// 面试异常中断时回补次数（同样以 session_id 幂等）
func (m *defaultUser) RefundCredit(ctx context.Context, in *RefundCreditReq, opts ...grpc.CallOption) (*RefundCreditResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.RefundCredit(ctx, in, opts...)
}
