// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package user

import (
	"context"

	"github.com/rotbit/whetstone/app/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeductCreditReq    = pb.DeductCreditReq
	DeductCreditResp   = pb.DeductCreditResp
	GetLatestResumeReq = pb.GetLatestResumeReq
	GetUserReq         = pb.GetUserReq
	LoginRep           = pb.LoginRep
	LoginResp          = pb.LoginResp
	RefundCreditReq    = pb.RefundCreditReq
	RefundCreditResp   = pb.RefundCreditResp
	RegisterReq        = pb.RegisterReq
	RegisterResp       = pb.RegisterResp
	ResumeInfo         = pb.ResumeInfo
	SaveJdReq          = pb.SaveJdReq
	SaveJdResp         = pb.SaveJdResp
	SaveResumeReq      = pb.SaveResumeReq
	SaveResumeResp     = pb.SaveResumeResp
	UserInfo           = pb.UserInfo

	User interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginRep, opts ...grpc.CallOption) (*LoginResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserInfo, error)
		// 保存 app-apis 已上传成功的 OSS 简历元数据；oss_url 用作跨重试幂等键。
		SaveResume(ctx context.Context, in *SaveResumeReq, opts ...grpc.CallOption) (*SaveResumeResp, error)
		// 查询用户最近上传的一份简历；未上传时返回 gRPC NotFound。
		GetLatestResume(ctx context.Context, in *GetLatestResumeReq, opts ...grpc.CallOption) (*ResumeInfo, error)
		// 保存一份目标岗位 JD，并返回数据库生成的主键。
		SaveJd(ctx context.Context, in *SaveJdReq, opts ...grpc.CallOption) (*SaveJdResp, error)
		// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
		DeductCredit(ctx context.Context, in *DeductCreditReq, opts ...grpc.CallOption) (*DeductCreditResp, error)
		// 面试异常中断时回补次数（同样以 session_id 幂等）
		RefundCredit(ctx context.Context, in *RefundCreditReq, opts ...grpc.CallOption) (*RefundCreditResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRep, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// 保存 app-apis 已上传成功的 OSS 简历元数据；oss_url 用作跨重试幂等键。
func (m *defaultUser) SaveResume(ctx context.Context, in *SaveResumeReq, opts ...grpc.CallOption) (*SaveResumeResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.SaveResume(ctx, in, opts...)
}

// 查询用户最近上传的一份简历；未上传时返回 gRPC NotFound。
func (m *defaultUser) GetLatestResume(ctx context.Context, in *GetLatestResumeReq, opts ...grpc.CallOption) (*ResumeInfo, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetLatestResume(ctx, in, opts...)
}

// 保存一份目标岗位 JD，并返回数据库生成的主键。
func (m *defaultUser) SaveJd(ctx context.Context, in *SaveJdReq, opts ...grpc.CallOption) (*SaveJdResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.SaveJd(ctx, in, opts...)
}

// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
func (m *defaultUser) DeductCredit(ctx context.Context, in *DeductCreditReq, opts ...grpc.CallOption) (*DeductCreditResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DeductCredit(ctx, in, opts...)
}

// 面试异常中断时回补次数（同样以 session_id 幂等）
func (m *defaultUser) RefundCredit(ctx context.Context, in *RefundCreditReq, opts ...grpc.CallOption) (*RefundCreditResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.RefundCredit(ctx, in, opts...)
}
