// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: question.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Question_PickQuestions_FullMethodName    = "/question.Question/PickQuestions"
	Question_GenerateFollowup_FullMethodName = "/question.Question/GenerateFollowup"
)

// QuestionClient is the client API for Question service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 题库 + RAG 个性化出题
type QuestionClient interface {
	// 按岗位 + 简历/JD 标签混合检索选题（向量 + 标签过滤 + rerank）
	PickQuestions(ctx context.Context, in *PickQuestionsReq, opts ...grpc.CallOption) (*PickQuestionsResp, error)
	// 基于候选人回答生成追问（项目深挖不走题库，LLM 现场生成）
	GenerateFollowup(ctx context.Context, in *GenerateFollowupReq, opts ...grpc.CallOption) (*GenerateFollowupResp, error)
}

type questionClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionClient(cc grpc.ClientConnInterface) QuestionClient {
	return &questionClient{cc}
}

func (c *questionClient) PickQuestions(ctx context.Context, in *PickQuestionsReq, opts ...grpc.CallOption) (*PickQuestionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickQuestionsResp)
	err := c.cc.Invoke(ctx, Question_PickQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionClient) GenerateFollowup(ctx context.Context, in *GenerateFollowupReq, opts ...grpc.CallOption) (*GenerateFollowupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateFollowupResp)
	err := c.cc.Invoke(ctx, Question_GenerateFollowup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServer is the server API for Question service.
// All implementations must embed UnimplementedQuestionServer
// for forward compatibility
//
// 题库 + RAG 个性化出题
type QuestionServer interface {
	// 按岗位 + 简历/JD 标签混合检索选题（向量 + 标签过滤 + rerank）
	PickQuestions(context.Context, *PickQuestionsReq) (*PickQuestionsResp, error)
	// 基于候选人回答生成追问（项目深挖不走题库，LLM 现场生成）
	GenerateFollowup(context.Context, *GenerateFollowupReq) (*GenerateFollowupResp, error)
	mustEmbedUnimplementedQuestionServer()
}

// UnimplementedQuestionServer must be embedded to have forward compatible implementations.
type UnimplementedQuestionServer struct {
}

func (UnimplementedQuestionServer) PickQuestions(context.Context, *PickQuestionsReq) (*PickQuestionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PickQuestions not implemented")
}
func (UnimplementedQuestionServer) GenerateFollowup(context.Context, *GenerateFollowupReq) (*GenerateFollowupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateFollowup not implemented")
}
func (UnimplementedQuestionServer) mustEmbedUnimplementedQuestionServer() {}

// UnsafeQuestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionServer will
// result in compilation errors.
type UnsafeQuestionServer interface {
	mustEmbedUnimplementedQuestionServer()
}

func RegisterQuestionServer(s grpc.ServiceRegistrar, srv QuestionServer) {
	s.RegisterService(&Question_ServiceDesc, srv)
}

func _Question_PickQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickQuestionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).PickQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_PickQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).PickQuestions(ctx, req.(*PickQuestionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Question_GenerateFollowup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateFollowupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServer).GenerateFollowup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Question_GenerateFollowup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServer).GenerateFollowup(ctx, req.(*GenerateFollowupReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Question_ServiceDesc is the grpc.ServiceDesc for Question service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Question_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "question.Question",
	HandlerType: (*QuestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PickQuestions",
			Handler:    _Question_PickQuestions_Handler,
		},
		{
			MethodName: "GenerateFollowup",
			Handler:    _Question_GenerateFollowup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "question.proto",
}
