// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateOrderReq struct {
	Sku string `json:"sku"` // pack_3 | monthly
}

type CreateOrderResp struct {
	OutTradeNo string `json:"outTradeNo"`
	PayUrl     string `json:"payUrl"`
}

type CreateSessionReq struct {
	Position string `json:"position"`          // 目标岗位，如 go-backend
	Mode     string `json:"mode,default=text"` // text | voice（M2）
	ResumeId int64  `json:"resumeId,optional"`
	JdId     int64  `json:"jdId,optional"`
}

type CreateSessionResp struct {
	SessionId string `json:"sessionId"`
	WsUrl     string `json:"wsUrl"`
}

type GetReportReq struct {
	SessionId string `path:"sessionId"`
}

type GetReportResp struct {
	State       string   `json:"state"` // generating | done
	Summary     string   `json:"summary"`
	RadarJson   string   `json:"radarJson"`
	Suggestions string   `json:"suggestions"`
	Items       []QaItem `json:"items"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type ListSessionsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=10"`
}

type ListSessionsResp struct {
	Total int64         `json:"total"`
	List  []SessionItem `json:"list"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type QaItem struct {
	Seq      int    `json:"seq"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
	Score    int    `json:"score"`
	Feedback string `json:"feedback"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type ResumeResp struct {
	ResumeId   int64  `json:"resumeId"`
	ParsedJson string `json:"parsedJson"` // 结构化简历（项目/技能/经历）
	ParseState string `json:"parseState"`
}

type SaveJdReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type SaveJdResp struct {
	JdId int64 `json:"jdId"`
}

type SessionItem struct {
	SessionId string `json:"sessionId"`
	Position  string `json:"position"`
	Mode      string `json:"mode"`
	State     string `json:"state"` // ongoing | finished | reported
	StartedAt int64  `json:"startedAt"`
}

type TokenResp struct {
	AccessToken string `json:"accessToken"`
	ExpireAt    int64  `json:"expireAt"`
}

type UploadResumeResp struct {
	ResumeId   int64  `json:"resumeId"`
	ParseState string `json:"parseState"` // parsing | done | failed
}

type UserInfoResp struct {
	Id      int64  `json:"id"`
	Phone   string `json:"phone"`
	Plan    string `json:"plan"`
	Credits int64  `json:"credits"`
}
