// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: interview.proto

package interview

import (
	"context"

	"github.com/yourname/whetstone/app/interview/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EndSessionReq      = pb.EndSessionReq
	EndSessionResp     = pb.EndSessionResp
	GetSessionStateReq = pb.GetSessionStateReq
	SessionState       = pb.SessionState
	StartSessionReq    = pb.StartSessionReq
	StartSessionResp   = pb.StartSessionResp
	SubmitAnswerReq    = pb.SubmitAnswerReq
	SubmitAnswerResp   = pb.SubmitAnswerResp

	Interview interface {
		// 初始化状态机，返回开场白与第一题
		StartSession(ctx context.Context, in *StartSessionReq, opts ...grpc.CallOption) (*StartSessionResp, error)
		// 提交候选人回答 → 引擎决策：追问 / 下一题 / 结束
		SubmitAnswer(ctx context.Context, in *SubmitAnswerReq, opts ...grpc.CallOption) (*SubmitAnswerResp, error)
		// 提前结束（触发报告任务入队）
		EndSession(ctx context.Context, in *EndSessionReq, opts ...grpc.CallOption) (*EndSessionResp, error)
		// ws 断线重连时恢复会话状态
		GetSessionState(ctx context.Context, in *GetSessionStateReq, opts ...grpc.CallOption) (*SessionState, error)
	}

	defaultInterview struct {
		cli zrpc.Client
	}
)

func NewInterview(cli zrpc.Client) Interview {
	return &defaultInterview{
		cli: cli,
	}
}

// 初始化状态机，返回开场白与第一题
func (m *defaultInterview) StartSession(ctx context.Context, in *StartSessionReq, opts ...grpc.CallOption) (*StartSessionResp, error) {
	client := pb.NewInterviewClient(m.cli.Conn())
	return client.StartSession(ctx, in, opts...)
}

// 提交候选人回答 → 引擎决策：追问 / 下一题 / 结束
func (m *defaultInterview) SubmitAnswer(ctx context.Context, in *SubmitAnswerReq, opts ...grpc.CallOption) (*SubmitAnswerResp, error) {
	client := pb.NewInterviewClient(m.cli.Conn())
	return client.SubmitAnswer(ctx, in, opts...)
}

// 提前结束（触发报告任务入队）
func (m *defaultInterview) EndSession(ctx context.Context, in *EndSessionReq, opts ...grpc.CallOption) (*EndSessionResp, error) {
	client := pb.NewInterviewClient(m.cli.Conn())
	return client.EndSession(ctx, in, opts...)
}

// ws 断线重连时恢复会话状态
func (m *defaultInterview) GetSessionState(ctx context.Context, in *GetSessionStateReq, opts ...grpc.CallOption) (*SessionState, error) {
	client := pb.NewInterviewClient(m.cli.Conn())
	return client.GetSessionState(ctx, in, opts...)
}
