// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: interview.proto

package server

import (
	"context"

	"github.com/yourname/whetstone/app/interview/rpc/internal/logic/interview"
	"github.com/yourname/whetstone/app/interview/rpc/internal/svc"
	"github.com/yourname/whetstone/app/interview/rpc/pb"
)

type InterviewServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInterviewServer
}

func NewInterviewServer(svcCtx *svc.ServiceContext) *InterviewServer {
	return &InterviewServer{
		svcCtx: svcCtx,
	}
}

// 初始化状态机，返回开场白与第一题
func (s *InterviewServer) StartSession(ctx context.Context, in *pb.StartSessionReq) (*pb.StartSessionResp, error) {
	l := interviewlogic.NewStartSessionLogic(ctx, s.svcCtx)
	return l.StartSession(in)
}

// 提交候选人回答 → 引擎决策：追问 / 下一题 / 结束
func (s *InterviewServer) SubmitAnswer(ctx context.Context, in *pb.SubmitAnswerReq) (*pb.SubmitAnswerResp, error) {
	l := interviewlogic.NewSubmitAnswerLogic(ctx, s.svcCtx)
	return l.SubmitAnswer(in)
}

// 提前结束（触发报告任务入队）
func (s *InterviewServer) EndSession(ctx context.Context, in *pb.EndSessionReq) (*pb.EndSessionResp, error) {
	l := interviewlogic.NewEndSessionLogic(ctx, s.svcCtx)
	return l.EndSession(in)
}

// ws 断线重连时恢复会话状态
func (s *InterviewServer) GetSessionState(ctx context.Context, in *pb.GetSessionStateReq) (*pb.SessionState, error) {
	l := interviewlogic.NewGetSessionStateLogic(ctx, s.svcCtx)
	return l.GetSessionState(in)
}
