// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: question.proto

package server

import (
	"context"

	"github.com/rotbit/whetstone/app/question/rpc/internal/logic/question"
	"github.com/rotbit/whetstone/app/question/rpc/internal/svc"
	"github.com/rotbit/whetstone/app/question/rpc/pb"
)

type QuestionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedQuestionServer
}

func NewQuestionServer(svcCtx *svc.ServiceContext) *QuestionServer {
	return &QuestionServer{
		svcCtx: svcCtx,
	}
}

// 按岗位 + 简历/JD 标签混合检索选题（向量 + 标签过滤 + rerank）
func (s *QuestionServer) PickQuestions(ctx context.Context, in *pb.PickQuestionsReq) (*pb.PickQuestionsResp, error) {
	l := questionlogic.NewPickQuestionsLogic(ctx, s.svcCtx)
	return l.PickQuestions(in)
}

// 基于候选人回答生成追问（项目深挖不走题库，LLM 现场生成）
func (s *QuestionServer) GenerateFollowup(ctx context.Context, in *pb.GenerateFollowupReq) (*pb.GenerateFollowupResp, error) {
	l := questionlogic.NewGenerateFollowupLogic(ctx, s.svcCtx)
	return l.GenerateFollowup(in)
}
