// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: question.proto

package question

import (
	"context"

	"github.com/rotbit/whetstone/app/question/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateFollowupReq  = pb.GenerateFollowupReq
	GenerateFollowupResp = pb.GenerateFollowupResp
	PickQuestionsReq     = pb.PickQuestionsReq
	PickQuestionsResp    = pb.PickQuestionsResp
	QuestionItem         = pb.QuestionItem

	Question interface {
		// 按岗位 + 简历/JD 标签混合检索选题（向量 + 标签过滤 + rerank）
		PickQuestions(ctx context.Context, in *PickQuestionsReq, opts ...grpc.CallOption) (*PickQuestionsResp, error)
		// 基于候选人回答生成追问（项目深挖不走题库，LLM 现场生成）
		GenerateFollowup(ctx context.Context, in *GenerateFollowupReq, opts ...grpc.CallOption) (*GenerateFollowupResp, error)
	}

	defaultQuestion struct {
		cli zrpc.Client
	}
)

func NewQuestion(cli zrpc.Client) Question {
	return &defaultQuestion{
		cli: cli,
	}
}

// 按岗位 + 简历/JD 标签混合检索选题（向量 + 标签过滤 + rerank）
func (m *defaultQuestion) PickQuestions(ctx context.Context, in *PickQuestionsReq, opts ...grpc.CallOption) (*PickQuestionsResp, error) {
	client := pb.NewQuestionClient(m.cli.Conn())
	return client.PickQuestions(ctx, in, opts...)
}

// 基于候选人回答生成追问（项目深挖不走题库，LLM 现场生成）
func (m *defaultQuestion) GenerateFollowup(ctx context.Context, in *GenerateFollowupReq, opts ...grpc.CallOption) (*GenerateFollowupResp, error) {
	client := pb.NewQuestionClient(m.cli.Conn())
	return client.GenerateFollowup(ctx, in, opts...)
}
