// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	auth "github.com/yourname/whetstone/app/apis/cmd/app-apis/internal/handler/auth"
	interview "github.com/yourname/whetstone/app/apis/cmd/app-apis/internal/handler/interview"
	system "github.com/yourname/whetstone/app/apis/cmd/app-apis/internal/handler/system"
	user "github.com/yourname/whetstone/app/apis/cmd/app-apis/internal/handler/user"
	websocket "github.com/yourname/whetstone/app/apis/cmd/app-apis/internal/handler/websocket"
	"github.com/yourname/whetstone/app/apis/cmd/app-apis/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sessions",
				Handler: interview.CreateSessionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sessions",
				Handler: interview.ListSessionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sessions/:sessionId/report",
				Handler: interview.GetReportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/interview"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: system.HealthHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/jd",
				Handler: user.SaveJdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/orders",
				Handler: user.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/resume",
				Handler: user.GetResumeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/resume/upload",
				Handler: user.UploadResumeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: websocket.WebsocketHandler(serverCtx),
			},
		},
	)
}
