// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: interview.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Interview_StartSession_FullMethodName    = "/interview.Interview/StartSession"
	Interview_SubmitAnswer_FullMethodName    = "/interview.Interview/SubmitAnswer"
	Interview_EndSession_FullMethodName      = "/interview.Interview/EndSession"
	Interview_GetSessionState_FullMethodName = "/interview.Interview/GetSessionState"
)

// InterviewClient is the client API for Interview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 面试引擎：状态机推进与追问决策（核心业务逻辑）
// 状态机：开场 → 项目深挖 → 基础知识 → 场景算法 → 候选人反问 → 收尾
type InterviewClient interface {
	// 初始化状态机，返回开场白与第一题
	StartSession(ctx context.Context, in *StartSessionReq, opts ...grpc.CallOption) (*StartSessionResp, error)
	// 提交候选人回答 → 引擎决策：追问 / 下一题 / 结束
	SubmitAnswer(ctx context.Context, in *SubmitAnswerReq, opts ...grpc.CallOption) (*SubmitAnswerResp, error)
	// 提前结束（触发报告任务入队）
	EndSession(ctx context.Context, in *EndSessionReq, opts ...grpc.CallOption) (*EndSessionResp, error)
	// ws 断线重连时恢复会话状态
	GetSessionState(ctx context.Context, in *GetSessionStateReq, opts ...grpc.CallOption) (*SessionState, error)
}

type interviewClient struct {
	cc grpc.ClientConnInterface
}

func NewInterviewClient(cc grpc.ClientConnInterface) InterviewClient {
	return &interviewClient{cc}
}

func (c *interviewClient) StartSession(ctx context.Context, in *StartSessionReq, opts ...grpc.CallOption) (*StartSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResp)
	err := c.cc.Invoke(ctx, Interview_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerReq, opts ...grpc.CallOption) (*SubmitAnswerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResp)
	err := c.cc.Invoke(ctx, Interview_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewClient) EndSession(ctx context.Context, in *EndSessionReq, opts ...grpc.CallOption) (*EndSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResp)
	err := c.cc.Invoke(ctx, Interview_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interviewClient) GetSessionState(ctx context.Context, in *GetSessionStateReq, opts ...grpc.CallOption) (*SessionState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionState)
	err := c.cc.Invoke(ctx, Interview_GetSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterviewServer is the server API for Interview service.
// All implementations must embed UnimplementedInterviewServer
// for forward compatibility
//
// 面试引擎：状态机推进与追问决策（核心业务逻辑）
// 状态机：开场 → 项目深挖 → 基础知识 → 场景算法 → 候选人反问 → 收尾
type InterviewServer interface {
	// 初始化状态机，返回开场白与第一题
	StartSession(context.Context, *StartSessionReq) (*StartSessionResp, error)
	// 提交候选人回答 → 引擎决策：追问 / 下一题 / 结束
	SubmitAnswer(context.Context, *SubmitAnswerReq) (*SubmitAnswerResp, error)
	// 提前结束（触发报告任务入队）
	EndSession(context.Context, *EndSessionReq) (*EndSessionResp, error)
	// ws 断线重连时恢复会话状态
	GetSessionState(context.Context, *GetSessionStateReq) (*SessionState, error)
	mustEmbedUnimplementedInterviewServer()
}

// UnimplementedInterviewServer must be embedded to have forward compatible implementations.
type UnimplementedInterviewServer struct {
}

func (UnimplementedInterviewServer) StartSession(context.Context, *StartSessionReq) (*StartSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedInterviewServer) SubmitAnswer(context.Context, *SubmitAnswerReq) (*SubmitAnswerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedInterviewServer) EndSession(context.Context, *EndSessionReq) (*EndSessionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedInterviewServer) GetSessionState(context.Context, *GetSessionStateReq) (*SessionState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionState not implemented")
}
func (UnimplementedInterviewServer) mustEmbedUnimplementedInterviewServer() {}

// UnsafeInterviewServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterviewServer will
// result in compilation errors.
type UnsafeInterviewServer interface {
	mustEmbedUnimplementedInterviewServer()
}

func RegisterInterviewServer(s grpc.ServiceRegistrar, srv InterviewServer) {
	s.RegisterService(&Interview_ServiceDesc, srv)
}

func _Interview_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interview_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServer).StartSession(ctx, req.(*StartSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interview_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interview_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServer).SubmitAnswer(ctx, req.(*SubmitAnswerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interview_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interview_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServer).EndSession(ctx, req.(*EndSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interview_GetSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterviewServer).GetSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interview_GetSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterviewServer).GetSessionState(ctx, req.(*GetSessionStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Interview_ServiceDesc is the grpc.ServiceDesc for Interview service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interview_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interview.Interview",
	HandlerType: (*InterviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _Interview_StartSession_Handler,
		},
		{
			MethodName: "SubmitAnswer",
			Handler:    _Interview_SubmitAnswer_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _Interview_EndSession_Handler,
		},
		{
			MethodName: "GetSessionState",
			Handler:    _Interview_GetSessionState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interview.proto",
}
