// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.19.4
// source: interview.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NextAction int32

const (
	NextAction_FOLLOWUP NextAction = 0 // 追问（最多 2 层）
	NextAction_NEXT     NextAction = 1 // 下一题
	NextAction_FINISH   NextAction = 2 // 面试结束
)

// Enum value maps for NextAction.
var (
	NextAction_name = map[int32]string{
		0: "FOLLOWUP",
		1: "NEXT",
		2: "FINISH",
	}
	NextAction_value = map[string]int32{
		"FOLLOWUP": 0,
		"NEXT":     1,
		"FINISH":   2,
	}
)

func (x NextAction) Enum() *NextAction {
	p := new(NextAction)
	*p = x
	return p
}

func (x NextAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NextAction) Descriptor() protoreflect.EnumDescriptor {
	return file_interview_proto_enumTypes[0].Descriptor()
}

func (NextAction) Type() protoreflect.EnumType {
	return &file_interview_proto_enumTypes[0]
}

func (x NextAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NextAction.Descriptor instead.
func (NextAction) EnumDescriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{0}
}

type StartSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId    int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Position  string `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	ResumeId  int64  `protobuf:"varint,4,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	JdId      int64  `protobuf:"varint,5,opt,name=jd_id,json=jdId,proto3" json:"jd_id,omitempty"`
}

func (x *StartSessionReq) Reset() {
	*x = StartSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionReq) ProtoMessage() {}

func (x *StartSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionReq.ProtoReflect.Descriptor instead.
func (*StartSessionReq) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartSessionReq) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *StartSessionReq) GetResumeId() int64 {
	if x != nil {
		return x.ResumeId
	}
	return 0
}

func (x *StartSessionReq) GetJdId() int64 {
	if x != nil {
		return x.JdId
	}
	return 0
}

type StartSessionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opening  string `protobuf:"bytes,1,opt,name=opening,proto3" json:"opening,omitempty"`   // 开场白
	Question string `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"` // 第一题
	Seq      int32  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *StartSessionResp) Reset() {
	*x = StartSessionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResp) ProtoMessage() {}

func (x *StartSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResp.ProtoReflect.Descriptor instead.
func (*StartSessionResp) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResp) GetOpening() string {
	if x != nil {
		return x.Opening
	}
	return ""
}

func (x *StartSessionResp) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *StartSessionResp) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type SubmitAnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq       int32  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Answer    string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *SubmitAnswerReq) Reset() {
	*x = SubmitAnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerReq) ProtoMessage() {}

func (x *SubmitAnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerReq.ProtoReflect.Descriptor instead.
func (*SubmitAnswerReq) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitAnswerReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitAnswerReq) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SubmitAnswerReq) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type SubmitAnswerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action NextAction `protobuf:"varint,1,opt,name=action,proto3,enum=interview.NextAction" json:"action,omitempty"`
	Reply  string     `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"` // 面试官回应（追问内容 / 下一题 / 收尾语）
	Seq    int32      `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *SubmitAnswerResp) Reset() {
	*x = SubmitAnswerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitAnswerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResp) ProtoMessage() {}

func (x *SubmitAnswerResp) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResp.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResp) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitAnswerResp) GetAction() NextAction {
	if x != nil {
		return x.Action
	}
	return NextAction_FOLLOWUP
}

func (x *SubmitAnswerResp) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *SubmitAnswerResp) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type EndSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *EndSessionReq) Reset() {
	*x = EndSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionReq) ProtoMessage() {}

func (x *EndSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionReq.ProtoReflect.Descriptor instead.
func (*EndSessionReq) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{4}
}

func (x *EndSessionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type EndSessionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *EndSessionResp) Reset() {
	*x = EndSessionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndSessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResp) ProtoMessage() {}

func (x *EndSessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResp.ProtoReflect.Descriptor instead.
func (*EndSessionResp) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{5}
}

func (x *EndSessionResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetSessionStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *GetSessionStateReq) Reset() {
	*x = GetSessionStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSessionStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStateReq) ProtoMessage() {}

func (x *GetSessionStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStateReq.ProtoReflect.Descriptor instead.
func (*GetSessionStateReq) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionStateReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase         string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"` // 状态机所处阶段
	Seq           int32  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	FollowupDepth int32  `protobuf:"varint,3,opt,name=followup_depth,json=followupDepth,proto3" json:"followup_depth,omitempty"`
	LastQuestion  string `protobuf:"bytes,4,opt,name=last_question,json=lastQuestion,proto3" json:"last_question,omitempty"`
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interview_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_interview_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_interview_proto_rawDescGZIP(), []int{7}
}

func (x *SessionState) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SessionState) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SessionState) GetFollowupDepth() int32 {
	if x != nil {
		return x.FollowupDepth
	}
	return 0
}

func (x *SessionState) GetLastQuestion() string {
	if x != nil {
		return x.LastQuestion
	}
	return ""
}

var File_interview_proto protoreflect.FileDescriptor

var file_interview_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x22, 0x97, 0x01, 0x0a,
	0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x13, 0x0a, 0x05, 0x6a, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6a, 0x64, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73,
	0x65, 0x71, 0x22, 0x5a, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x69,
	0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x4e,
	0x65, 0x78, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x2e, 0x0a, 0x0d, 0x45, 0x6e, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x45, 0x6e, 0x64,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x33, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x82, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x75, 0x70, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x75, 0x70, 0x44, 0x65, 0x70, 0x74, 0x68,
	0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x30, 0x0a, 0x0a, 0x4e, 0x65, 0x78, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x55, 0x50, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x49, 0x4e, 0x49, 0x53, 0x48, 0x10, 0x02, 0x32, 0xab, 0x02, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x47, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65,
	0x77, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x47,
	0x0a, 0x0c, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1a,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65,
	0x77, 0x2e, 0x45, 0x6e, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x45, 0x6e, 0x64, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x49, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interview_proto_rawDescOnce sync.Once
	file_interview_proto_rawDescData = file_interview_proto_rawDesc
)

func file_interview_proto_rawDescGZIP() []byte {
	file_interview_proto_rawDescOnce.Do(func() {
		file_interview_proto_rawDescData = protoimpl.X.CompressGZIP(file_interview_proto_rawDescData)
	})
	return file_interview_proto_rawDescData
}

var file_interview_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interview_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_interview_proto_goTypes = []interface{}{
	(NextAction)(0),            // 0: interview.NextAction
	(*StartSessionReq)(nil),    // 1: interview.StartSessionReq
	(*StartSessionResp)(nil),   // 2: interview.StartSessionResp
	(*SubmitAnswerReq)(nil),    // 3: interview.SubmitAnswerReq
	(*SubmitAnswerResp)(nil),   // 4: interview.SubmitAnswerResp
	(*EndSessionReq)(nil),      // 5: interview.EndSessionReq
	(*EndSessionResp)(nil),     // 6: interview.EndSessionResp
	(*GetSessionStateReq)(nil), // 7: interview.GetSessionStateReq
	(*SessionState)(nil),       // 8: interview.SessionState
}
var file_interview_proto_depIdxs = []int32{
	0, // 0: interview.SubmitAnswerResp.action:type_name -> interview.NextAction
	1, // 1: interview.Interview.StartSession:input_type -> interview.StartSessionReq
	3, // 2: interview.Interview.SubmitAnswer:input_type -> interview.SubmitAnswerReq
	5, // 3: interview.Interview.EndSession:input_type -> interview.EndSessionReq
	7, // 4: interview.Interview.GetSessionState:input_type -> interview.GetSessionStateReq
	2, // 5: interview.Interview.StartSession:output_type -> interview.StartSessionResp
	4, // 6: interview.Interview.SubmitAnswer:output_type -> interview.SubmitAnswerResp
	6, // 7: interview.Interview.EndSession:output_type -> interview.EndSessionResp
	8, // 8: interview.Interview.GetSessionState:output_type -> interview.SessionState
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_interview_proto_init() }
func file_interview_proto_init() {
	if File_interview_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interview_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSessionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitAnswerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndSessionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSessionStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interview_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interview_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interview_proto_goTypes,
		DependencyIndexes: file_interview_proto_depIdxs,
		EnumInfos:         file_interview_proto_enumTypes,
		MessageInfos:      file_interview_proto_msgTypes,
	}.Build()
	File_interview_proto = out.File
	file_interview_proto_rawDesc = nil
	file_interview_proto_goTypes = nil
	file_interview_proto_depIdxs = nil
}
