// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	User_Register_FullMethodName        = "/user.User/Register"
	User_Login_FullMethodName           = "/user.User/Login"
	User_GetUser_FullMethodName         = "/user.User/GetUser"
	User_SaveResume_FullMethodName      = "/user.User/SaveResume"
	User_GetLatestResume_FullMethodName = "/user.User/GetLatestResume"
	User_SaveJd_FullMethodName          = "/user.User/SaveJd"
	User_DeductCredit_FullMethodName    = "/user.User/DeductCredit"
	User_RefundCredit_FullMethodName    = "/user.User/RefundCredit"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 用户域内部服务：用户信息 / 简历 / JD / 次数幂等扣减
type UserClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginRep, opts ...grpc.CallOption) (*LoginResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserInfo, error)
	// 保存 app-apis 已上传成功的 OSS 简历元数据；oss_url 用作跨重试幂等键。
	SaveResume(ctx context.Context, in *SaveResumeReq, opts ...grpc.CallOption) (*SaveResumeResp, error)
	// 查询用户最近上传的一份简历；未上传时返回 gRPC NotFound。
	GetLatestResume(ctx context.Context, in *GetLatestResumeReq, opts ...grpc.CallOption) (*ResumeInfo, error)
	// 保存一份目标岗位 JD，并返回数据库生成的主键。
	SaveJd(ctx context.Context, in *SaveJdReq, opts ...grpc.CallOption) (*SaveJdResp, error)
	// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
	DeductCredit(ctx context.Context, in *DeductCreditReq, opts ...grpc.CallOption) (*DeductCreditResp, error)
	// 面试异常中断时回补次数（同样以 session_id 幂等）
	RefundCredit(ctx context.Context, in *RefundCreditReq, opts ...grpc.CallOption) (*RefundCreditResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, User_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginRep, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, User_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SaveResume(ctx context.Context, in *SaveResumeReq, opts ...grpc.CallOption) (*SaveResumeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveResumeResp)
	err := c.cc.Invoke(ctx, User_SaveResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetLatestResume(ctx context.Context, in *GetLatestResumeReq, opts ...grpc.CallOption) (*ResumeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeInfo)
	err := c.cc.Invoke(ctx, User_GetLatestResume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SaveJd(ctx context.Context, in *SaveJdReq, opts ...grpc.CallOption) (*SaveJdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveJdResp)
	err := c.cc.Invoke(ctx, User_SaveJd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeductCredit(ctx context.Context, in *DeductCreditReq, opts ...grpc.CallOption) (*DeductCreditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductCreditResp)
	err := c.cc.Invoke(ctx, User_DeductCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RefundCredit(ctx context.Context, in *RefundCreditReq, opts ...grpc.CallOption) (*RefundCreditResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundCreditResp)
	err := c.cc.Invoke(ctx, User_RefundCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
//
// 用户域内部服务：用户信息 / 简历 / JD / 次数幂等扣减
type UserServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginRep) (*LoginResp, error)
	GetUser(context.Context, *GetUserReq) (*UserInfo, error)
	// 保存 app-apis 已上传成功的 OSS 简历元数据；oss_url 用作跨重试幂等键。
	SaveResume(context.Context, *SaveResumeReq) (*SaveResumeResp, error)
	// 查询用户最近上传的一份简历；未上传时返回 gRPC NotFound。
	GetLatestResume(context.Context, *GetLatestResumeReq) (*ResumeInfo, error)
	// 保存一份目标岗位 JD，并返回数据库生成的主键。
	SaveJd(context.Context, *SaveJdReq) (*SaveJdResp, error)
	// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
	DeductCredit(context.Context, *DeductCreditReq) (*DeductCreditResp, error)
	// 面试异常中断时回补次数（同样以 session_id 幂等）
	RefundCredit(context.Context, *RefundCreditReq) (*RefundCreditResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServer) Login(context.Context, *LoginRep) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServer) GetUser(context.Context, *GetUserReq) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServer) SaveResume(context.Context, *SaveResumeReq) (*SaveResumeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveResume not implemented")
}
func (UnimplementedUserServer) GetLatestResume(context.Context, *GetLatestResumeReq) (*ResumeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestResume not implemented")
}
func (UnimplementedUserServer) SaveJd(context.Context, *SaveJdReq) (*SaveJdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveJd not implemented")
}
func (UnimplementedUserServer) DeductCredit(context.Context, *DeductCreditReq) (*DeductCreditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductCredit not implemented")
}
func (UnimplementedUserServer) RefundCredit(context.Context, *RefundCreditReq) (*RefundCreditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefundCredit not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginRep))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SaveResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SaveResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SaveResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SaveResume(ctx, req.(*SaveResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetLatestResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestResumeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetLatestResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetLatestResume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetLatestResume(ctx, req.(*GetLatestResumeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SaveJd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveJdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SaveJd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SaveJd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SaveJd(ctx, req.(*SaveJdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeductCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductCreditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeductCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeductCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeductCredit(ctx, req.(*DeductCreditReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RefundCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundCreditReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RefundCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_RefundCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RefundCredit(ctx, req.(*RefundCreditReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _User_GetUser_Handler,
		},
		{
			MethodName: "SaveResume",
			Handler:    _User_SaveResume_Handler,
		},
		{
			MethodName: "GetLatestResume",
			Handler:    _User_GetLatestResume_Handler,
		},
		{
			MethodName: "SaveJd",
			Handler:    _User_SaveJd_Handler,
		},
		{
			MethodName: "DeductCredit",
			Handler:    _User_DeductCredit_Handler,
		},
		{
			MethodName: "RefundCredit",
			Handler:    _User_RefundCredit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
