// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"github.com/rotbit/whetstone/app/user/rpc/internal/logic/user"
	"github.com/rotbit/whetstone/app/user/rpc/internal/svc"
	"github.com/rotbit/whetstone/app/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginRep) (*pb.LoginResp, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.UserInfo, error) {
	l := userlogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 保存 app-apis 已上传成功的 OSS 简历元数据；oss_url 用作跨重试幂等键。
func (s *UserServer) SaveResume(ctx context.Context, in *pb.SaveResumeReq) (*pb.SaveResumeResp, error) {
	l := userlogic.NewSaveResumeLogic(ctx, s.svcCtx)
	return l.SaveResume(in)
}

// 查询用户最近上传的一份简历；未上传时返回 gRPC NotFound。
func (s *UserServer) GetLatestResume(ctx context.Context, in *pb.GetLatestResumeReq) (*pb.ResumeInfo, error) {
	l := userlogic.NewGetLatestResumeLogic(ctx, s.svcCtx)
	return l.GetLatestResume(in)
}

// 保存一份目标岗位 JD，并返回数据库生成的主键。
func (s *UserServer) SaveJd(ctx context.Context, in *pb.SaveJdReq) (*pb.SaveJdResp, error) {
	l := userlogic.NewSaveJdLogic(ctx, s.svcCtx)
	return l.SaveJd(in)
}

// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
func (s *UserServer) DeductCredit(ctx context.Context, in *pb.DeductCreditReq) (*pb.DeductCreditResp, error) {
	l := userlogic.NewDeductCreditLogic(ctx, s.svcCtx)
	return l.DeductCredit(in)
}

// 面试异常中断时回补次数（同样以 session_id 幂等）
func (s *UserServer) RefundCredit(ctx context.Context, in *pb.RefundCreditReq) (*pb.RefundCreditResp, error) {
	l := userlogic.NewRefundCreditLogic(ctx, s.svcCtx)
	return l.RefundCredit(in)
}
