// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"github.com/rotbit/whetstone/app/user/rpc/internal/logic/user"
	"github.com/rotbit/whetstone/app/user/rpc/internal/svc"
	"github.com/rotbit/whetstone/app/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResp, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginRep) (*pb.LoginResp, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *pb.GetUserReq) (*pb.UserInfo, error) {
	l := userlogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 面试开始前扣减次数；session_id 作幂等键，重复调用不重复扣
func (s *UserServer) DeductCredit(ctx context.Context, in *pb.DeductCreditReq) (*pb.DeductCreditResp, error) {
	l := userlogic.NewDeductCreditLogic(ctx, s.svcCtx)
	return l.DeductCredit(in)
}

// 面试异常中断时回补次数（同样以 session_id 幂等）
func (s *UserServer) RefundCredit(ctx context.Context, in *pb.RefundCreditReq) (*pb.RefundCreditResp, error) {
	l := userlogic.NewRefundCreditLogic(ctx, s.svcCtx)
	return l.RefundCredit(in)
}
